name: Deploy React Native App

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install -g react-native-cli
          npm install

      - name: Create directories for Android bundle
        run: mkdir -p android/app/src/main/assets/

      - name: Build React Native app
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android && ./gradlew assembleRelease

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./android/app/build/outputs/apk/release/

  deploy:
    needs: build_and_deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./android/app/build/outputs/apk/release/

      - name: Deploy APK using scp with generated RSA private key
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./android/app/build/outputs/apk/release/app-release.apk maelys@51.178.30.100:~/
